//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyVideoWin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfInfoAddress {
            get {
                return ((string)(this["ConfInfoAddress"]));
            }
            set {
                this["ConfInfoAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfManagementAddress {
            get {
                return ((string)(this["ConfManagementAddress"]));
            }
            set {
                this["ConfManagementAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hexmeethjt")]
        public string URLProtocol {
            get {
                return ((string)(this["URLProtocol"]));
            }
            set {
                this["URLProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cloud.hexmeet.com")]
        public string CloudServerAddress {
            get {
                return ((string)(this["CloudServerAddress"]));
            }
            set {
                this["CloudServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cloudcenter.hexmeet.com")]
        public string CloudLocationServerAddress {
            get {
                return ((string)(this["CloudLocationServerAddress"]));
            }
            set {
                this["CloudLocationServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://swinfo.cninnovatel.com")]
        public string SoftwareUpdateAddress {
            get {
                return ((string)(this["SoftwareUpdateAddress"]));
            }
            set {
                this["SoftwareUpdateAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows")]
        public string SoftwareUpdateFlag {
            get {
                return ((string)(this["SoftwareUpdateFlag"]));
            }
            set {
                this["SoftwareUpdateFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.hexmeet.hjt")]
        public string SoftwareUpdateBundleId {
            get {
                return ((string)(this["SoftwareUpdateBundleId"]));
            }
            set {
                this["SoftwareUpdateBundleId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("appinfo.json")]
        public string SoftwareUpdateAppInfo {
            get {
                return ((string)(this["SoftwareUpdateAppInfo"]));
            }
            set {
                this["SoftwareUpdateAppInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoftwareUpdateAppInfoPrefix {
            get {
                return ((string)(this["SoftwareUpdateAppInfoPrefix"]));
            }
            set {
                this["SoftwareUpdateAppInfoPrefix"] = value;
            }
        }
    }
}
